### ISSUE TITLE
Support different NetCDF paths for C and Fortran

### ISSUE THREAD

**Issue by jwallwork23** [fetch4/GISS-GC#1]
Note that not setting `GC_BIN`, `GC_F_BIN`, `GC_INCLUDE`, `GC_F_INCLUDE`, `GC_LIB`, and `GC_F_LIB` environment variables correctly leads to build failures. As I demonstrated in https://github.com/fetch4/geos-chem/pull/1, this can be reduced to two environment variables: the NetCDF home paths for C and Fortran.

Currently, the `modelErc` created by GISS only defines `NETCDFHOME`, which I believe corresponds to the Fortran libraries. It would be better if two paths could be set, to account for the case where the C and Fortran paths differ.

**Comment by joewallwork** [comment]
Closed by #3.
