### ISSUE TITLE
Protect branches

### ISSUE THREAD

**Issue by joewallwork** [fetch4/GISS-GC#6]
Currently, none of the branches of this repository are protected. Turning on branch protection for the main branch is strongly recommended.

Before turning on branch protection, we should establish which branch is to be considered the "main" one. Given that this repo is an offshoot of GISS and GEOS-Chem (which each have their own `main` branch), we might consider using a different name, such as `giss-gc`, or even protecting several branches corresponding to different versions, e.g., `giss-gc-14.3.1`. If we take the version approach, do we need to account for the GISS version, as well as the GEOS-Chem one?

**Comment by joewallwork** [comment]
As discussed in the meeting, we now have a single [`develop`](https://github.com/fetch4/GISS-GC/tree/develop) branch, which will correspond to the most recent version of GEOS-Chem for which the coupling is working.

So, in addressing this issue, perhaps we set up branch protections for both `main` and `develop`?

**Comment by joewallwork** [comment]
Please also do the same for the corresponding branches of the [GEOS-Chem fork](https://github.com/fetch4/geos-chem).

**Comment by AmyOctoCat** [comment]
I've set up branch protection on `main` and `develop` for the GEOS-Chem fork, but I don't think I have permission to do so on GISS-GC. Will look into this further.

**Comment by joewallwork** [comment]
Thanks @AmyOctoCat! I've sent you an invite just now.

**Comment by AmyOctoCat** [comment]
Thanks! Should be all done now. :)

**Comment by joewallwork** [comment]
All looks good, thanks.
